### ISSUE TITLE
Check boxes don't uncheck as expected

### ISSUE THREAD

**Issue by RoriCremer** [DataBiosphere/data-explorer#205]
If you select multiple checkboxes and then try to unselect the first box you selected by clicking on it, it will unselect the last box, not the one you just clicked on.

To reproduce:
In one of the facetCards:
Click the top checkbox so that it is selected
Click the a second checkbox so that it is selected
Click on the top checkbox again (as you would to uncheck it) --note that it is the other checkbox which deselects.

**Comment by melissachang** [comment]
Thanks!

Malathi, can you take a look? https://test-data-explorer.appspot.com/ doesn't have the problem, but master does.
