### ISSUE TITLE
FR: Help identify missingness in sample data

### ISSUE THREAD

**Issue by mbookman** [DataBiosphere/data-explorer#223]
https://www.tandfonline.com/doi/abs/10.1080/10543400903238959?src=recsys&journalCode=lbps20

> Missing data can pose substantial risk of reaching incorrect conclusions from clinical studies. Imputation for the missing values is common, but can supply only an approximate result desired to be “close enough” to the intended true result. Prevention optimally addresses the issue.

Data Explorer can be a great tool to aid researchers in identifying missingness of data.

One area where we can do this is with identifying participants who are missing samples.
For example, currently we are not able to display:

  "Has WGS CRAM... Yes: N, No: M"

when a samples table does not include a record for a participant. The logic for displaying this today depends on the samples table having a record for the participant with the CRAM column value empty. This is not how most data is stored.

**Comment by melissachang** [comment]
I talked to Bryan. I think it's better if the dataset is explicit about this; that is, the BigQuery table has empty values.

You mention showing "Has WGS CRAM" at the participant level. But the current Samples Overview facet/"Has WGS CRAM" is at the sample level. So I think this feature should be sample level as well. Also, it would be too confusing in our implementation to have some has_ fields at the participant level, and other has_ fields at the sample level.

Assuming this feature request is sample level -- If a participant doesn't have a row in the samples table, we don't know their sample id. So we don't have a place to _has_wgs_cram=false.

Regarding "This is not how most data is stored.". From what I understand, existing dataset BigQuery tables don't have file columns in the first place. (If you know of any exceptions, please let me know.) So we are already asking people to change their BigQuery tables.

If the Data Curator wants "Has WGS CRAM" facet, I think it's reasonable to ask Data Curator to add additional sample rows.

**Comment by melissachang** [comment]
Discussed offline, we think it's better for Data Curator to be explicit
