### ISSUE TITLE
Expose facets url parameters in appspot url

### ISSUE THREAD

**Issue by melissachang** [DataBiosphere/data-explorer#311]
Right now, when I do stuff in Data Explorer (add a facet or create a filter), the Chrome tab URL stays the same (`https://test-data-explorer.appspot.com`). It would be nice if the URL changed. That way, people could send each other links representing cohorts (and added facets).
 
The API server `facets` request does contain this information:

```
https://test-data-explorer.appspot.com/api/facets?filter=samples.verily-public-data.human_genome_variants.1000_genomes_sample_info.LC_Pilot_Centers%3DSC%7CSamples%20Overview%3DHas%20WGS%20Low%20Coverage%20CRAM&extraFacets=samples.verily-public-data.human_genome_variants.1000_genomes_sample_info.LC_Pilot_Centers
```

So we need to support:

1. Go to `https://test-data-explorer.appspot.com` and click on a bar. The Chrome tab url should change.
1. Go to `https://test-data-explorer.appspot.com` and add a facet. The Chrome tab url should change.
1. Accessing URL from 1 or 2 directly should work.

**Comment by wnojopra** [comment]
Fixed by #315
