### ISSUE TITLE
Allow for time series data to have NULL values in the `time_series_column`

### ISSUE THREAD

**Issue by mbookman** [DataBiosphere/data-explorer#347]
In AMP PD, we have a `visit_month` column in most every clinical table which records the month from baseline in which the data was collected. For some tables the field is not always populated: one study collected this data and recorded the date, while others collected the data  but attached no date.

Currently data explorer cannot handle NULL values in the configured `time_series_column`.

It _may_ be the case that for such data elements, the time that the data was collected is not interesting most of the time. In such cases, having #346 might make this a non-issue. But an alternative would be to add a default to the display such that, for example, any values with a NULL `visit_month` were displayed as an "Unknown" month.

**Comment by melissachang** [comment]
Fixed by #349 (and some commits in data-explorer-indexers repo).

@wnojopra , you are now unblocked to set up the new AMP PD DE.

**Comment by wnojopra** [comment]
Great, thanks!
