### ISSUE TITLE
After faceted search, rerender in one stage instead of two

### ISSUE THREAD

**Issue by melissachang** [DataBiosphere/data-explorer#63]
To best illustrate this issue, put `import time; time.sleep(1)` into facets_controller.py facets_get().

After clicking on a checkbox, rerendering happens in two stages:

1. Checkbox has checkmark, unchecked Age values turn gray
![stage1](https://user-images.githubusercontent.com/10929390/39067037-201165fe-448c-11e8-8713-8b1dc8a520be.png)

2. New facet data returned from backend. All numbers outside of Age facet update. (Age total count also updates.)
![stage2](https://user-images.githubusercontent.com/10929390/39067041-22959bba-448c-11e8-810e-2fd3ae9d228d.png)

Two stages is jarring. Rerendering should happen in one stage. We should hold off on 1) until after backend RPC completes.

AFAICT, [Boardwalk](https://ucsc-cgp.org/boardwalk) doesn't have this problem.

**Comment by alahwa** [comment]
Some UX guidance here would be necessary for us to approach this. Maybe it's better to give instant feedback via changing colors and some kind of indication that we're fetching additional data to prevent blocking the UI? Or maybe it's better to load all in one go as you stated? Or if elasticsearch always has good performance, maybe it's not something that users would really notice at all?

Looking at Boardwalk, they are rendering in two stages as well. Notice that when you click a checkbox, the count `0 / X` updates to `1 / X` before the data is fetched and the rest of the UI updates.

**Comment by melissachang** [comment]
Strange, I can't reproduce with Boardwalk. There's a noticeable lag after I click the checkbox, then the 1/X and rest of page updates all at once.

I think we should copy Boardwalk (or what I observe Boardwalk to be doing). It's simple and effective. I don't see a reason to add spinners.

Most of the time I don't notice it, but occasionally I do. When it happens, it's very jarring to me.
