### ISSUE TITLE
Use a static IP for the Elasticsearch ILB

### ISSUE THREAD

**Issue by alahwa** [DataBiosphere/data-explorer#77]
This reduces the amount of config required from the user and simplifies deployment.

https://cloud.google.com/compute/docs/ip-addresses/reserve-static-internal-ip-address
https://cloud.google.com/kubernetes-engine/docs/how-to/internal-load-balancing#config

**Comment by melissachang** [comment]
I think it would be cleaner to use `kubectl` to get the IP. For example, what if the static IP we want to reserve is already taken? You can do something like this:
```
epxort ELASTICSEARCH_URL_REPLACE_ME=`kubectl get svc elasticsearch | grep elasticsearch | awk '{print $4}'`
sed -i "s/ELASTICSEARCH_URL_REPLACE_ME/$ELASTICSEARCH_URL_REPLACE_ME/" app.yaml
```

**Comment by melissachang** [comment]
Deployment is now, I think this would actually complicate deployment
